# Generated by Django 3.2.6 on 2021-08-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='bookValue',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='high',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='low',
        ),
        migrations.CreateModel(
            name='StockBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currentAssets', models.FloatField()),
                ('cash', models.FloatField()),
                ('shortTermInvestments', models.FloatField()),
                ('totalReceivables', models.FloatField()),
                ('totalInventory', models.FloatField()),
                ('otherCurrentAssets', models.FloatField()),
                ('nonCurrentAssets', models.FloatField()),
                ('longTermInvestments', models.FloatField()),
                ('totalAssets', models.FloatField()),
                ('accountsPayable', models.FloatField()),
                ('otherCurrentLiabilites', models.FloatField()),
                ('totalLongTermDebt', models.FloatField()),
                ('otherLiabilities', models.FloatField()),
                ('totalLiabilites', models.FloatField()),
                ('commonStock', models.FloatField()),
                ('capitalSurplus', models.FloatField()),
                ('minorityInterest', models.FloatField()),
                ('totalEquity', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.stock')),
            ],
        ),
    ]
