# Generated by Django 3.2.4 on 2021-08-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_auto_20210815_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currentPrice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='stocks',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='stocks',
            field=models.ManyToManyField(to='watchlist.Stock'),
        ),
        migrations.DeleteModel(
            name='StockBalanceSheet',
        ),
    ]
