# Generated by Django 3.2.6 on 2021-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_auto_20210815_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='currentPrice',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='accountsPayable',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='capitalSurplus',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='cash',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='commonStock',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='currentAssets',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='longTermInvestments',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='minorityInterest',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='nonCurrentAssets',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='otherCurrentAssets',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='otherCurrentLiabilities',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='otherLiabilities',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='shortTermInvestments',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalAssets',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalEquity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalInventory',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalLiabilities',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalLongTermDebt',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalReceivables',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
