# Generated by Django 3.2.4 on 2021-11-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_auto_20210821_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entry', models.FloatField()),
                ('sl', models.FloatField()),
                ('target', models.FloatField()),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
    ]
