# Generated by Django 3.2.4 on 2021-11-11 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_pendingtrades'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtrades',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 11, 22, 19, 13, 886495)),
            preserve_default=False,
        ),
    ]
