# Generated by Django 3.2.4 on 2022-02-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chapters_count', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('feature_image', models.ImageField(upload_to='images/')),
                ('color', models.CharField(max_length=25)),
                ('upload_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('feature_image', models.ImageField(default='images/rubber-10.png', upload_to='images/')),
                ('slug', models.SlugField(default='')),
                ('quote', models.CharField(blank=True, max_length=1024, null=True)),
                ('upload_on', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.module')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
        ),
    ]
